name: pipelene for webdriverIO
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 12
        - name: Install
          run: npm install
        - name: User config
          run: npm config set user 0
        - name: Permission
          run: npm config set unsafe-perm true
        - name: Test
          run: npm run test:headless
        - name: Generate HTML report
          run: npm run allure:generate
        - name: Upload Results
          uses: actions/upload-artifact@v1
          if: always()
          with:
           name: allure-results
           path: ./allure-results # Name of the folder with allure results
        - name: Publishing Allure artifact to Github Actions
          uses: actions/upload-artifact@v2
          if: always()
          with:
           name: allure-report
           path: allure-report
        - name: Deploy report page
          uses: peaceiris/actions-gh-pages@v3
          with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: allure-report
           user_name: 'github-actions[bot]'
           user_email: 'github-actions[bot]@users.noreply.github.com'
